name:                LangToGroup
version:             0.1.0.0
github:              "YaccConstructor/LangToGroup"
license:             "Apache-2.0"
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

# extra-source-files:
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YaccConstructor/LangToGroup#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- vector
- HaTeX >= 3.20.0.0
- regex-tdfa
#- MissingH
- fgl
- graphviz
- text
- bytestring
- megaparsec
- prettyprinter >= 1.7.0
- pretty-simple
- hlint
- HaskellForMaths
- deepseq
- rando
- mtl
- split
- lens
- template-haskell
- haskell-src-meta
- extra
- ansi-terminal

ghc-options: 
    -Wall
    -fno-warn-type-defaults

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -funfolding-use-threshold=16
  - -optc-O3
  - -fno-warn-orphans

executables:
  LangToGroup-printer:
    main:                Main.hs
    source-dirs:         printers
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-orphans
    dependencies:
    - LangToGroup
    - matrix >= 0.3.6.1
    - cli  

  LangToGroup-cli:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LangToGroup

tests:
  LangToGroup-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LangToGroup
    - HUnit
    - test-framework
    - test-framework-hunit
